version: "2"
services:
  postgres:
    image: 'postgres:14.1-alpine'
    ports:
      - '5432:5432'
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/